---
title: Installeer Thonny
hero_image: images/banner.png
description: Installeer de Thonny Python editor.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - 
    title: Installeer Thonny
