---
title: Instalace editoru Thonny
hero_image: images/banner.png
description: Instalace Thonny - Python editoru.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Instalace editoru Thonny
