---
title: Installera Thonny
hero_image: images/banner.png
description: Installera Thonny Python-redigeraren.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - 
    title: Installera Thonny
