---
title: Εγκατάσταση Thonny
hero_image: images/banner.png
description: Εγκατάστησε τον επεξεργαστή Thonny για Python.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Εγκατάσταση Thonny
